---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-viktor.serviceAccountName" . }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-viktor.serviceAccountName" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
    verbs:
      - get
      - list
      - delete
  - apiGroups:
      - ""
    resources:
      - pods/eviction
    verbs:
      - create

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-viktor.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kube-viktor.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kube-viktor.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
