---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-viktor
  namespace: kube-viktor

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-viktor
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
    verbs:
      - get
      - list
      - delete
  - apiGroups:
      - ""
    resources:
      - pods/eviction
    verbs:
      - create

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-viktor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-viktor
subjects:
  - kind: ServiceAccount
    name: kube-viktor
    namespace: kube-viktor
