---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kube-victor-sample-payload
spec:
  maxUnavailable: "10%"
  selector:
    matchLabels:
      app.kubernetes.io/name: sample-payload
